/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diyetisyenodev;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trapper344
 */
public class doktorgirisi extends javax.swing.JFrame {

    /**
     * Creates new form doktorgirisi
     */
    public doktorgirisi() {
        initComponents();
        
        String baslik[] = new String[]{ "TC Kimlik No", "Adı", "Soyadı", "Randevu Tarihi","Randevu Saati"};  

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = con.createStatement();
            
            String sorgu21 = "select * from uyeler inner join muayenealma on uyeler.id=muayenealma.uye_id where muayenealma.kayit='1' order by uyeler.adi ";
            
            st = con.createStatement();
            rs = st.executeQuery(sorgu21);
            
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("tc_no"),  
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("randevu_tarihi"),
                    rs.getString("randevu_saati"),
                    
                };
                i++;
            }
           
            table_randevular.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        String baslik1[] = new String[]{ "TC Kimlik No", "Adı", "Soyadı", "Randevu Saati"};  

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = con.createStatement();
            
            String sorgu2 = "select * from uyeler inner join muayenealma on uyeler.id=muayenealma.uye_id where muayenealma.kayit='1' order by uyeler.adi ";
            
            rs = st.executeQuery(sorgu2);
            
            rs.last();
            int kayitsayisi1 = rs.getRow();
            rs.beforeFirst();

            Object data1[][] = new Object[kayitsayisi1][];
            int i = 0;

            while (rs.next()) {

                data1[i] = new Object[]{  
                    
                    rs.getString("tc_no"),  
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("randevu_saati"),
                    
                };
                i++;
            }
           
            table_randevular.setModel(new DefaultTableModel(data1, baslik1));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        hastabilgileri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        txt_soyadi = new javax.swing.JTextField();
        txt_cinsiyet = new javax.swing.JTextField();
        txt_dogumtarihi = new javax.swing.JTextField();
        txt_dogumyeri = new javax.swing.JTextField();
        txt_yas = new javax.swing.JTextField();
        txt_kilo = new javax.swing.JTextField();
        txt_boy = new javax.swing.JTextField();
        txt_sikayet = new javax.swing.JTextField();
        txt_aciklama = new javax.swing.JTextField();
        btn_ara = new javax.swing.JButton();
        btn_kaydet = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        randevularim = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_randevular = new javax.swing.JTable();
        randevuara = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ran_gun = new javax.swing.JComboBox<>();
        ran_ay = new javax.swing.JComboBox<>();
        ran_yil = new javax.swing.JComboBox<>();
        btn_randevuaraara = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_randevuara = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Doktor Girisi");

        jLabel2.setText("Tc Kimlik:");

        jLabel3.setText("Adi:");

        jLabel4.setText("Soyadi:");

        jLabel5.setText("Cinsiyet:");

        jLabel6.setText("Dogum Tarihi:");

        jLabel7.setText("Dogum Yeri:");

        jLabel8.setText("Yas:");

        jLabel9.setText("Kilo:");

        jLabel10.setText("Boy:");

        jLabel11.setText("Sikayet:");

        jLabel12.setText("Aciklama:");

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        btn_guncelle.setText("Guncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hastabilgileriLayout = new javax.swing.GroupLayout(hastabilgileri);
        hastabilgileri.setLayout(hastabilgileriLayout);
        hastabilgileriLayout.setHorizontalGroup(
            hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hastabilgileriLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_cinsiyet)
                                    .addComponent(txt_soyadi)
                                    .addComponent(txt_ad)
                                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_dogumtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_dogumyeri, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ara)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(hastabilgileriLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_sikayet)
                                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_boy, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_kilo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_yas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(hastabilgileriLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        hastabilgileriLayout.setVerticalGroup(
            hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hastabilgileriLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hastabilgileriLayout.createSequentialGroup()
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_dogumtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_dogumyeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_ara))
                        .addGap(46, 46, 46)
                        .addComponent(btn_kaydet)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guncelle))
                    .addGroup(hastabilgileriLayout.createSequentialGroup()
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_kilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_boy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_sikayet, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(hastabilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hastabilgileriLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12))
                            .addGroup(hastabilgileriLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        jTabbedPane3.addTab("Hasta Bilgileri", hastabilgileri);

        table_randevular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TC Kimlik", "Adi", "Soyadi", "Randevu Tarihi", "Randevu Saati"
            }
        ));
        jScrollPane1.setViewportView(table_randevular);

        javax.swing.GroupLayout randevularimLayout = new javax.swing.GroupLayout(randevularim);
        randevularim.setLayout(randevularimLayout);
        randevularimLayout.setHorizontalGroup(
            randevularimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevularimLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        randevularimLayout.setVerticalGroup(
            randevularimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevularimLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Randevularim", randevularim);

        jLabel13.setText("Tarih:");

        ran_gun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gun", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ran_ay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ay", "OCAK", "SUBAT", "MART", "NISAN", "MAYIS", "HAZIRAN", "TEMMUZ", "AGUSTOS", "EYLUL", "EKIM", "KASIM", "ARALIK" }));

        ran_yil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yil", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        btn_randevuaraara.setText("Ara");
        btn_randevuaraara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_randevuaraaraActionPerformed(evt);
            }
        });

        table_randevuara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TC Kimlik", "Adi", "Soyadi", "Randevu Saati"
            }
        ));
        jScrollPane2.setViewportView(table_randevuara);

        javax.swing.GroupLayout randevuaraLayout = new javax.swing.GroupLayout(randevuara);
        randevuara.setLayout(randevuaraLayout);
        randevuaraLayout.setHorizontalGroup(
            randevuaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevuaraLayout.createSequentialGroup()
                .addGroup(randevuaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(randevuaraLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(48, 48, 48)
                        .addComponent(ran_gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ran_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ran_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btn_randevuaraara))
                    .addGroup(randevuaraLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        randevuaraLayout.setVerticalGroup(
            randevuaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(randevuaraLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(randevuaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ran_gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ran_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ran_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_randevuaraara))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Randevu Ara", randevuara);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = con.createStatement();
            
            String sorgu2 = "select * from uyeler INNER JOIN hastamuayene where uyeler.id=hastamuayene.uye_id and hastamuayene.tc_no='"+txt_tc.getText()+"'";
            
            rs = st.executeQuery(sorgu2);
            rs.last();
            
            int sayi = rs.getRow();
            
            if(sayi>0){
                
                txt_ad.setText(rs.getString("adi"));
                txt_soyadi.setText(rs.getString("soyadi"));
                txt_dogumtarihi.setText(rs.getString("dtarihi"));
                txt_cinsiyet.setText(rs.getString("cinsiyeti"));
                txt_dogumyeri.setText(rs.getString("dyeri"));                
                
                txt_yas.setText(rs.getString("yas"));
                txt_kilo.setText(rs.getString("kilo"));
                txt_boy.setText(rs.getString("boy"));
                txt_sikayet.setText(rs.getString("sikayet"));
                txt_aciklama.setText(rs.getString("aciklama"));
                
            }
            
            else if(sayi==0){
                
                con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
                st = con.createStatement();

                String sorgu21 = "select * from uyeler where tc_no='"+txt_tc.getText()+"'";
                rs = st.executeQuery(sorgu21);
                rs.next();

                int sayi1 = rs.getRow();

                if(sayi1>0){

                    txt_ad.setText(rs.getString("adi"));
                    txt_soyadi.setText(rs.getString("soyadi"));
                    txt_dogumtarihi.setText(rs.getString("dtarihi"));
                    txt_cinsiyet.setText(rs.getString("cinsiyet"));
                    txt_dogumyeri.setText(rs.getString("dyeri"));
            
                }
                else{
                    JOptionPane.showMessageDialog(null, "Böyle bir kullanıcı kayıtlı değil");
                }
                
            }
            
 
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
    }//GEN-LAST:event_btn_araActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        try {
            String tc_no=txt_tc.getText();
            String adi=txt_ad.getText();
            String soyadi=txt_soyadi.getText();
            String dtarihi=txt_dogumtarihi.getText();
            String dyeri=txt_dogumyeri.getText();
            String cinsiyeti=txt_cinsiyet.getText();
            String sikayet=txt_sikayet.getText();
            String yas=txt_yas.getText();
            String kilo=txt_kilo.getText();
            String boy=txt_boy.getText();
            String aciklama=txt_aciklama.getText();

            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            com.mysql.jdbc.Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = (com.mysql.jdbc.Statement) con.createStatement();
            
            String sql = "Update hastamuayene set tc_no='"+tc_no+"',adi='"+adi+"',soyadi='"+soyadi+"',dtarihi='"+dtarihi+"'"
                    +",dyeri='"+dyeri+"',cinsiyet='"+cinsiyeti+"',sikayet='"+sikayet+"',yas='"+yas+"',kilo='"+kilo+"'"
                    +",boy='"+boy+"',aciklama='"+aciklama+"' where tc_no='"+tc_no+"'";

            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Sayın "+ adi + " "+ soyadi + " İşleminiz Gerçekleşmiştir.");
           
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_randevuaraaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_randevuaraaraActionPerformed
      try {
              
        String gun=String.valueOf(ran_gun.getSelectedItem());
        String ay=String.valueOf(ran_ay.getSelectedItem());
        String yil=String.valueOf(ran_yil.getSelectedItem());        
        String randevu_tarihi=gun + " / " + ay + " / " + yil;
        
        String baslik[] = new String[]{ "TC Kimlik", "Adı", "Soyadı", "Randevu Saati"};  

            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = con.createStatement();
            
            String sorgu21 = "select * from uyeler inner join muayenealma on uyeler.id=muayenealma.uye_id where muayenealma.randevu_tarihi='"+randevu_tarihi+"' and muayenealma.kayit='1' order by uyeler.id";
            
            rs = st.executeQuery(sorgu21);
            rs.last();
            
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("tc_no"),  
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("randevu_saati"),
                    
                };
                i++;
            }
            
            table_randevuara.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());    
        }
        
    }//GEN-LAST:event_btn_randevuaraaraActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        try {
            String tc_no=txt_tc.getText();
            String adi=txt_ad.getText();
            String soyadi=txt_soyadi.getText();
            String dtarihi=txt_dogumtarihi.getText();
            String dyeri=txt_dogumyeri.getText();
            String cinsiyeti=txt_cinsiyet.getText();
            String sikayet=txt_sikayet.getText();
            String yas=txt_yas.getText();
            String kilo=txt_kilo.getText();
            String boy=txt_boy.getText();
            String aciklama=txt_aciklama.getText();
             

            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            com.mysql.jdbc.Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/diyetisyen?useUnicode=true&characterEncoding=UTF8", "root", "desdes");
            st = (com.mysql.jdbc.Statement) con.createStatement();
            
            String sql = "INSERT INTO hastamuayene (tc_no,adi,soyadi,dtarihi,dyeri,cinsiyet,sikayet,yas,kilo,boy,aciklama)"
                    +"VALUES ('"+tc_no+"', '"+adi+"', '"+soyadi+"', '"+dtarihi+"','"+dyeri+"', '"+cinsiyeti+"', '"+sikayet+"',"
                    + "'"+yas+"', '"+kilo+"', '"+boy+"', '"+aciklama+"')";

            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Sayın "+ adi + " "+ soyadi + " İşleminiz Gerçekleşmiştir.");
           
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }//GEN-LAST:event_btn_kaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktorgirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktorgirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktorgirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktorgirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktorgirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_randevuaraara;
    private javax.swing.JPanel hastabilgileri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> ran_ay;
    private javax.swing.JComboBox<String> ran_gun;
    private javax.swing.JComboBox<String> ran_yil;
    private javax.swing.JPanel randevuara;
    private javax.swing.JPanel randevularim;
    private javax.swing.JTable table_randevuara;
    private javax.swing.JTable table_randevular;
    private javax.swing.JTextField txt_aciklama;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_boy;
    private javax.swing.JTextField txt_cinsiyet;
    private javax.swing.JTextField txt_dogumtarihi;
    private javax.swing.JTextField txt_dogumyeri;
    private javax.swing.JTextField txt_kilo;
    private javax.swing.JTextField txt_sikayet;
    private javax.swing.JTextField txt_soyadi;
    private javax.swing.JTextField txt_tc;
    private javax.swing.JTextField txt_yas;
    // End of variables declaration//GEN-END:variables
}
